# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greenhouse_titul', models.CharField(help_text='\u0422\u0438\u043f \u0442\u0435\u043f\u043b\u0438\u0446\u044b', max_length=200)),
                ('greenhouse_width', models.CharField(help_text='\u0428\u0438\u0440\u0438\u043d\u0430', max_length=200)),
                ('greenhouse_height', models.CharField(help_text='\u0412\u044b\u0441\u043e\u0442\u0430', max_length=200)),
                ('greenhouse_frontImage', models.ImageField(help_text='\u0412\u0438\u0434 \u0441 \u0431\u043e\u043a\u0443', null=True, upload_to='images', verbose_name='photo')),
                ('greenhouse_image', models.ImageField(help_text='\u041e\u0431\u0449\u0438\u0439 \u0432\u0438\u0434', null=True, upload_to='images', verbose_name='photo')),
            ],
            options={
                'db_table': "'greenhouse",
            },
        ),
    ]
