# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenhouse',
            old_name='greenhouse_titul',
            new_name='greenhouse_title',
        ),
        migrations.AlterModelTable(
            name='greenhouse',
            table='\u0422\u0438\u043f \u0442\u0435\u043f\u043b\u0438\u0446\u044b',
        ),
    ]
