# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170315_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galery_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_place', models.ImageField(help_text='\u041e\u0431\u0449\u0438\u0439 \u0432\u0438\u0434', null=True, upload_to='images', verbose_name='photo')),
                ('photo_album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Galery')),
            ],
            options={
                'db_table': '\u0424\u043e\u0442\u043e',
            },
        ),
    ]
