# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_galery_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='\u0418\u043c\u044f \u043a\u043b\u0438\u0435\u043d\u0442\u0430', max_length=200, null=True)),
                ('client_number', models.CharField(help_text='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430 \u043a\u043b\u0438\u0435\u043d\u0442\u0430', max_length=200, null=True)),
                ('client_email', models.CharField(help_text='Email \u043a\u043b\u0438\u0435\u043d\u0442\u0430', max_length=200, null=True)),
                ('client_describtion', models.TextField(help_text='\u0421\u0434\u0435\u0441\u044c \u0412\u044b \u043c\u043e\u0436\u0435\u0442\u0435 \u043e\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u0437\u0430\u043c\u0435\u0442\u043a\u0443', null=True)),
            ],
            options={
                'db_table': '\u041a\u043b\u0438\u0435\u043d\u0442',
            },
        ),
    ]
